[package]
name = "asyncapiv3"
version = "0.1.2"
edition = "2021"
authors = ["Davide Ghilardi <dghila@d71.dev>"]

description = "Asyncapi v3 types and utilities"
keywords = [ "asyncapi", "v3" ]
repository = "https://github.com/dghilardi/asyncapiv3"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", optional = true }
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = { version = "1.0", optional = true }
asyncapi = "0.2.0"

[dev-dependencies]
serde_yaml = "0.9"

[features]
builder_unstable = ["log", "thiserror"]
